version: 0.2

phases:
  install:
    commands:
      - apt update -y
      - apt install curl -y
      - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - apt install nodejs
      - npm install gulp -g
      runtime-versions:
        node: 12.13.1
  pre_build:
    commands:
      - echo "Nothing to do in this phase"
  build:
    commands:
      - echo "Build started on `date`"
      - gulp dist
      - echo "Error loading page" > dist/error.html
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - dist/**/*