export const SET_EMAIL="SET_EMAIL";
export const SET_STACK="SET_STACK";
export const REMOVE_STACK="REMOVE_STACK";
export const SET_DATABASE="SET_DATABASE";
export const REMOVE_DATABASE="REMOVE_DATABASE";
export const SET_ADDONS="SET_ADDONS";
export const REMOVE_ADDONS="REMOVE_ADDONS";
export const SET_ACTIVE_STEP="SET_ACTIVE_STEP";
